orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@1.0.0
version: 2.1
jobs:
  build:
    working_directory: ~/repos/crypto-tech
    docker:
      - image: microsoft/dotnet:3.0-sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - setup_remote_docker:
          docker_layer_caching: true
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          aws-access-key-id: ""
          aws-secret-access-key-id: ""
          create-repo: true
          region: "eu-west-2"
          dockerfile: Dockerfile
          path: ~/repos/crypto-tech
          tag: latest
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: ''
          cluster-name: ''
          service-name: ''
          container-image-name-updates: ''